### ISSUE TITLE
Reason for ffmpeg0.10 in KCP

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/ffmpeg0.10#1]
Hi, why was `ffmpeg0.10` added to KCP?

We have [ffmpeg v2.8.6 in main](https://github.com/KaOSx/main/tree/master/ffmpeg), so why add 0.10 to KCP? Shouldn't ffmpeg in main just do the job? If not, what is the difference between this version and the on in the main-repository? (Description doesn't provide any)

As far as I know, no other Packages depend on `ffmpeg0.10`.

**Comment by demmm** [comment]
This version contains older libs needed by some packages.  Probably those that needed it are removed.....

**Comment by Adurol** [comment]
If it is like this, I will open a Removel Candidate issue.
