### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/ffmpeg0.10#2]
This Package will be removed in 7 days from KCP.

Reason: **Orphan**

This specific version of ffmpeg doesn't seem to be needed by any other packages in KCP. An up-to-date version of ffmpeg is also maintained in [main](https://github.com/KaOSx/main/tree/master/ffmpeg).

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by forostm** [comment]
This dependency is required to [curlew](https://github.com/KaOS-Community-Packages/curlew/)

**Comment by Adurol** [comment]
Thanks for pointing out. It got added with KaOS-Community-Packages/curlew@d728c6c332056542a28530e82c6e1a7453b3a465, but I don't know why 2 different ffmpeg-version are used by curlew...
